### ISSUE TITLE
binary.py usage guide

### ISSUE THREAD

**Issue by mottosso** [westernx/mayatools#1]
Hi @mikeboers,

I just discovered this neat library via Google and was hoping to use it to read a binary file as though it were in Maya ASCII format, but I can't quite wrap my head around whether that's actually what it's for?

The end goal is to list each node from a scene file. Would it be possible to provide a snippet of how to achieve something along these lines?

The [final example](http://mayatools.readthedocs.org/en/latest/binary.html#interpreting-it-all) on Read The Docs hints towards the possibility of reading names of shape nodes.

**Comment by mikeboers** [comment]
You can certainly parse the raw binary format:

```
parser = mayatools.binary.Parser(open_file)
parser.parse_all()
```

However, the binary format does not self-describe, so while you have the structure, you don't really know what tags mean what and what data type they are. You need to make simple scenes to figure that out. And then you will find that there is sometimes quite a bit of ASCII data within the binary file. :stuck_out_tongue: 

Good luck!

**Comment by mottosso** [comment]
Thank @mikeboers, I ran the above, but it didn't return anything. I tried `.pprint()` but only got a binary representation.

How would I retrieve the `.notes` attribute of something like the `persp` node in a scene? Is that possible?

**Comment by mikeboers** [comment]
Since I wrote this parser, the file format switched to allow for 64bit values (the file will start with `FOR8`). I'm not reading those correctly.

Try this other project -> https://github.com/agibli/sansapp/blob/master/maya/binary.py

**Comment by mottosso** [comment]
Aah, I see. Thanks for the link, I'll give that a try.
